### ISSUE TITLE
047-update-fastskill-2

### ISSUE THREAD

**Issue by aroff** [gofastskill/fastskill#115]
# Update fastskill to latest aikit-sdk

## 1. Problem statement

The fastskill project currently uses `aikit-sdk` as a git dependency pinned to a specific revision (`845082113797e3eaf6fc8c0e9b3d48980d1e960c`) in `Cargo.lock`. This means builds use an outdated version of the SDK regardless of any new features, bug fixes, or API improvements available in the current `main` branch. The dependency update process requires advancing the lockfile revision and fixing any potential API compatibility issues that may have been introduced since the last update.

**Out of scope:** This specification does NOT include migrating from git dependencies to published crate versions, changing the dependency strategy (such as adding explicit rev pinning), or implementing local path-based development workflows.

## 2. Goals

1. Update the `aikit-sdk` git dependency to the latest `main` branch revision in `Cargo.lock`
2. Verify the codebase compiles successfully with the updated SDK version via `cargo check`
3. Ensure all existing tests pass with the updated SDK version via `cargo test`
4. Fix any API compatibility issues that arise from SDK changes in affected source files
5. Commit the updated lockfile and any necessary code changes with appropriate commit message

## 3. Current behavior

| Component | Role | Mutable at runtime? |
|-----------|------|-------------------|
| `Cargo.toml` | Declares aikit-sdk git dependency from main branch | No |
| `Cargo.lock` | Pins exact git revision (845082113797e3eaf6fc8c0e9b3d48980d1e960c) | No - only changed by cargo commands |
| `src/eval/runner.rs` | Uses aikit-sdk APIs for agent execution (run_agent_events, RunOptions, etc.) | No |
| `src/eval/trace.rs` | Converts aikit-sdk AgentEvent types to internal trace format | No |
| `src/cli/commands/sync.rs` | Uses aikit-sdk for agent metadata file resolution | No |

The current build flow uses the exact git revision specified in Cargo.lock. The resume flow after dependency updates requires running `cargo check` to verify compilation, then `cargo test` to ensure test compatibility, with potential code fixes for any API drift.

### Core Mechanism
The update process leverages Cargo's selective dependency update capability via `cargo update -p aikit-sdk`, which fetches the latest commit from the specified git branch and updates only that dependency's locked revision.

#### Agent Execution APIs (`src/eval/runner.rs`)
- `aikit_sdk::run_agent_events()` - Core agent execution function
- `aikit_sdk::RunOptions` - Configuration struct with methods like `with_yolo()`, `with_stream()`, `with_timeout()`, `with_current_dir()`, `with_model()`
- `aikit_sdk::RunResult` - Success result type with `exit_code()`, `stdout`, `stderr` fields
- `aikit_sdk::RunError` - Error enum with `TimedOut` variant containing `timeout`, `stderr` fields

#### Event Processing APIs (`src/eval/trace.rs`)
- `aikit_sdk::AgentEvent` - Event struct with `seq` field and `payload`
- `aikit_sdk::AgentEventPayload` - Enum with variants: `JsonLine(serde_json::Value)`, `RawLine(String)`, `RawBytes(Vec<u8>)`

#### Agent Metadata APIs (`src/cli/commands/sync.rs`)
- `aikit_sdk::instruction_file_with_override()` - Path resolution function
- `aikit_sdk::validate_agent_key()` - Agent key validation function
- `aikit_sdk::DeployError` - Error enum with variants: `AgentNotFound(String)`, `UnsupportedConcept { agent_key: String, .. }`

### Error Handling Strategy
API changes may manifest as compilation errors (missing methods, changed signatures) or runtime errors (changed enum variants, different error types). The implementation MUST handle both categories by updating imports, method calls, and error matching patterns as needed.

### Integration Points
The primary integration boundary is the FFI-style interface where fastskill calls into aikit-sdk for agent operations. Test integration occurs through the eval test suite which exercises agent execution paths.

### Command Interface
```rust
// Primary update command
cargo update -p aikit-sdk

// Verification commands  
cargo check
cargo test
```

### Critical Type Dependencies
```rust
// From aikit-sdk (current usage)
use aikit_sdk::{
    run_agent_events, AgentEvent, AgentEventPayload, RunOptions, RunResult, RunError,
    instruction_file_with_override, validate_agent_key, DeployError
};

// Core function signature
pub fn run_agent_events(
    agent_key: &str,
    prompt: &str, 
    options: RunOptions,
    event_callback: impl FnMut(AgentEvent)
) -> Result<RunResult, RunError>;
```

### File Modification Interface
```rust
// Files that MUST be updated if API changes
const AFFECTED_FILES: &[&str] = &[
    "src/eval/runner.rs",
    "src/eval/trace.rs", 
    "src/cli/commands/sync.rs"
];
```

## 6. Error codes

| Code | Category | Trigger |
|------|----------|---------|
| COMPILE_ERROR_SDK_API | Build failure | aikit-sdk API signature changed, requiring code updates |
| TEST_FAILURE_INTEGRATION | Test failure | eval integration tests fail due to SDK behavior changes |
| CARGO_UPDATE_FAILED | Dependency resolution | `cargo update -p aikit-sdk` fails due to git/network issues |

## 7. Acceptance criteria

1. `cargo update -p aikit-sdk` command executes successfully and updates the git revision in Cargo.lock
2. `cargo check` completes without compilation errors after the dependency update
3. `cargo test` passes all existing tests after the dependency update  
4. Any API compatibility fixes are applied to affected source files (runner.rs, trace.rs, sync.rs)
5. Changes are committed with a conventional commit message format (e.g., "chore: bump aikit-sdk git revision")
6. The updated Cargo.lock reflects a different git revision than 845082113797e3eaf6fc8c0e9b3d48980d1e960c
7. All aikit-sdk import statements in affected files remain valid after the update
8. No new clippy warnings are introduced in files that use aikit-sdk APIs
9. Integration tests in `tests/cli/eval_tests.rs` continue to pass without modification

### Before Implementation
- fastskill uses aikit-sdk git revision `845082113797e3eaf6fc8c0e9b3d48980d1e960c`
- All builds use this exact SDK revision regardless of upstream changes
- Manual lockfile inspection required to determine current SDK version
- Potential missing bug fixes or features from newer SDK versions

### After Implementation  
- fastskill uses the latest aikit-sdk git revision from main branch
- All builds use the updated SDK version with latest features and fixes
- Lockfile reflects current main branch tip at time of update
- Any API compatibility issues resolved through targeted code updates

## 9. Benefit of implementing this functionality

**Primary Value:** Keeps fastskill current with aikit-sdk improvements, ensuring access to latest features, performance improvements, and bug fixes from the upstream project.

**Risk Mitigation:** Regular dependency updates reduce the likelihood of large breaking changes accumulating over time, making future updates easier and less risky.

**Development Velocity:** Updated SDK may provide improved APIs, better error handling, or performance optimizations that benefit fastskill's eval and sync functionality.

**Security:** Ensures any security fixes in aikit-sdk are promptly incorporated into fastskill builds.

### Stage 1: Dependency Update
**Deliverable:** Updated Cargo.lock with new aikit-sdk git revision  
**Scope:** Execute `cargo update -p aikit-sdk` from project root  
**Dependencies:** None (blocking: none)

### Stage 2: Compilation Verification  
**Deliverable:** Successful compilation with updated dependency  
**Scope:** Run `cargo check` and resolve any compilation errors in runner.rs, trace.rs, sync.rs  
**Dependencies:** Stage 1 completion (blocking: dependency must be updated first)

### Stage 3: Test Verification
**Deliverable:** All tests passing with updated dependency  
**Scope:** Run `cargo test` (specifically eval_tests.rs integration tests) and fix any test failures  
**Dependencies:** Stage 2 completion (blocking: code must compile before testing)

### Stage 4: Code Quality Verification
**Deliverable:** No new warnings or linting issues  
**Scope:** Run `cargo clippy` on affected files to ensure no new warnings introduced  
**Dependencies:** Stage 3 completion (blocking: tests must pass before quality checks)

### Stage 5: Commit Changes
**Deliverable:** Git commit containing lockfile and any necessary code changes  
**Scope:** Commit Cargo.lock and modified source files with conventional commit message  
**Dependencies:** Stages 1-4 completion (blocking: all changes must be verified before commit)

## 11. Breaking changes

**For Users:** None - this is an internal dependency update with no user-facing API changes.

**For Developers:** Potential breaking changes if aikit-sdk has modified its public API since revision 845082113797e3eaf6fc8c0e9b3d48980d1e960c. These would manifest as compilation errors requiring code updates to match new API signatures.

**For CI/CD:** None expected - existing build pipeline should handle the updated dependency transparently.

## 12. Modified files and summary

| File/path | Summary of modifications |
|-----------|-------------------------|
| `Cargo.lock` | Update aikit-sdk git revision to latest main branch commit |
| `src/eval/runner.rs` | Fix any aikit-sdk API usage if run_agent_events, RunOptions, or error types changed |
| `src/eval/trace.rs` | Fix any aikit-sdk API usage if AgentEvent or AgentEventPayload changed |  
| `src/cli/commands/sync.rs` | Fix any aikit-sdk API usage if instruction_file_with_override, validate_agent_key, or DeployError changed |
| `tests/cli/eval_tests.rs` | No modifications expected (tests use fake agent binary) |

## 13. Dependencies

**External Dependencies:**
- **Git network access** to github.com/goaikit/aikit (blocking Stage 1) - required for cargo update
- **OpenAI API availability** (non-blocking, optional) - only affects tests that make actual API calls

**Internal Dependencies:** 
- **Rust toolchain availability** (blocking all stages) - required for cargo commands
- **Clean working directory** (recommended Stage 5) - for clean commit history

**Team Dependencies:** None - this is a self-contained technical update requiring no external coordination.

## 14. Proposed folder structure

No new files or directories are created by this change. The existing project structure remains unchanged:

```
/home/sysuser/ws001/gofastskill/fastskill/
├── Cargo.toml                    # Unchanged
├── Cargo.lock                    # Modified (updated revision)
├── src/
│   ├── eval/
│   │   ├── runner.rs             # Potentially modified
│   │   └── trace.rs              # Potentially modified  
│   └── cli/commands/
│       └── sync.rs               # Potentially modified
└── tests/cli/
    └── eval_tests.rs             # Unchanged
```

## 15. Design decisions

| # | Question | Decision | Rationale |
|---|----------|----------|-----------|
| 1 | Should we update only aikit-sdk or all dependencies? | Only aikit-sdk using `-p` flag | Minimizes risk by avoiding unrelated dependency changes |
| 2 | Should we pin to a specific revision after update? | No, maintain branch tracking | Preserves current dependency strategy as specified |
| 3 | How should we handle API breaking changes? | Fix immediately during update process | Ensures working state before commit |  
| 4 | Should we run full test suite or targeted tests? | Full test suite via `cargo test` | Comprehensive verification of compatibility |
| 5 | What commit message format should be used? | Conventional commits (chore: prefix) | Matches existing project conventions |

## 16. Out of scope (explicit)

- Migrating from git dependencies to published crate versions
- Adding explicit `rev = "<sha>"` pinning to Cargo.toml  
- Setting up local path dependencies for development
- Updating other dependencies beyond aikit-sdk
- Modifying the eval test framework or fake agent implementation
- Performance benchmarking of SDK changes
- Documentation updates for new SDK features
- Backward compatibility shims for older API patterns

## 17. References

**Key Files to Examine:**
- `/home/sysuser/ws001/gofastskill/fastskill/Cargo.toml` - Line 22: Current aikit-sdk dependency declaration
- `/home/sysuser/ws001/gofastskill/fastskill/Cargo.lock` - Line 46: Current git revision (845082113797e3eaf6fc8c0e9b3d48980d1e960c)
- `/home/sysuser/ws001/gofastskill/fastskill/src/eval/runner.rs` - Lines 7, 64-65: aikit-sdk imports and type usage
- `/home/sysuser/ws001/gofastskill/fastskill/src/eval/trace.rs` - Lines 3, 32-54: AgentEvent processing logic
- `/home/sysuser/ws001/gofastskill/fastskill/src/cli/commands/sync.rs` - Lines 11, 190-207: SDK integration functions

**Test References:**
- `/home/sysuser/ws001/gofastskill/fastskill/tests/cli/eval_tests.rs` - Integration tests for eval functionality

**External References:**
- https://github.com/goaikit/aikit - Upstream aikit-sdk repository
- Cargo documentation: https://doc.rust-lang.org/cargo/commands/cargo-update.html
